plugins:
  - "@typescript-eslint"
  - "react"
  - "jsx-a11y"
  - "react-hooks"
  - "jest"
  - "no-secrets"
  - "prettier"
  - "import"
extends:
  - 'plugin:@typescript-eslint/recommended'
  - "eslint:recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:jest/recommended"
  - "plugin:jsx-a11y/recommended"
  - "plugin:prettier/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:react/recommended"
  - "react-app"
rules:
  "no-secrets/no-secrets": "error"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
ignorePatterns:
  - "src/generated"